// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIBjCNnmwGVTis5PL0GFtAFGWp4X9Qui8',
    appId: '1:189080001206:web:29983e0ab7536d05f82417',
    messagingSenderId: '189080001206',
    projectId: 'studyforgeproject',
    authDomain: 'studyforgeproject.firebaseapp.com',
    storageBucket: 'studyforgeproject.firebasestorage.app',
    measurementId: 'G-JQL7MXFPBZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzM8_CV6pfQOPhfIErfMbWxHNNrKNpmAM',
    appId: '1:189080001206:android:c341164fa4e690a8f82417',
    messagingSenderId: '189080001206',
    projectId: 'studyforgeproject',
    storageBucket: 'studyforgeproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCIIFuwartA7PUMVbek5zl5iZobrqjRiU',
    appId: '1:189080001206:ios:6a872ec8503e908df82417',
    messagingSenderId: '189080001206',
    projectId: 'studyforgeproject',
    storageBucket: 'studyforgeproject.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCIIFuwartA7PUMVbek5zl5iZobrqjRiU',
    appId: '1:189080001206:ios:6a872ec8503e908df82417',
    messagingSenderId: '189080001206',
    projectId: 'studyforgeproject',
    storageBucket: 'studyforgeproject.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIBjCNnmwGVTis5PL0GFtAFGWp4X9Qui8',
    appId: '1:189080001206:web:8ce39661d058b2ccf82417',
    messagingSenderId: '189080001206',
    projectId: 'studyforgeproject',
    authDomain: 'studyforgeproject.firebaseapp.com',
    storageBucket: 'studyforgeproject.firebasestorage.app',
    measurementId: 'G-45EN5MKB03',
  );
}
